= SRFI nnn
:toc: macro
:toc-title:

== Title

*Command lines*

== Table of contents

toc::[]

== Author

Lassi Kortela

== Status

Draft

== Abstract

R^6^RS and R^7^RS define a *command-line* procedure. While a useful
baseline, the specification is not detailed enough to cover all
practical situations. This SRFI clarifies the definition of
*command-line* and adds a few related procedures. Precise semantics
for Unix and Windows are given. Scheme scripts, standalone
executables, compilation and REPL use are accounted for. Option
parsing is out of scope.

== Rationale

=== OS executables

When a Scheme implementation is run on a conventional operating
system, the OS runs an _executable_. An executable is a file that
contains a program in a format suitable for the OS. In the case of
Scheme, the executable can represent:

* A standalone Scheme program.

* A Scheme implementation.

* A virtual machine (such as the Java Virtual Machine or the .NET
  Common Language Runtime) hosting the Scheme implementation, which in
  turn hosts the Scheme program.

=== OS command lines

The OS gives the executable a _command line_. The command line is a
vector of strings. There is an extremely strong convention that the
first string represents the _command name_. Any remaining strings are
_command arguments_ interpreted differently by each program.

=== Command names are portable but not reliable

By convention, the command name is derived from the executable
filename in one of the following formats:

* An absolute pathname (`/usr/bin/emacs`)
* A relative pathname (`../bin/emacs`)
* A basename only with no directory part (`emacs`)

However, it is important to note that the command name is _an
arbitrary string_ that is stored _wholly separate_ from the executable
filename. A change in one does not necessarily affect the other.
Popular operating systems like Unix and Windows let programs easily
start other programs with an arbitrary command name. The name is not
validated in any way by the OS. That's why it is not a reliable hint
for determining the executable filename.

The upside of command lines, and hence command names, is that they are
extremely portable. Practically all general-purpose operating systems
provide them. As long as command names are used for display purposes
and not interpreted as filenames, programs using them are portable and
reliable.

=== Executable filenames are reliable but not portable

It is equally important to realize that the executable filename is
_not_ arbitrary like the command name is. When the OS process is
launched, the executable filename has to be valid. (Any one executable
generally has many valid filenames since we can use relative
filenames, make hard links and symbolic links in the file system,
etc.) Unix-like operating systems generally allow the executable file
to be moved, renamed or deleted after the executable has been loaded
into memory. While the executable filename was guaranteed to be valid
at the time of process creation, it does not necessarily remain valid
throughout the lifetime of the process. However, it is generally both
more reliable and more specific than the command name.

Unfortunately, system calls that retrieve the executable filename are
extremely non-portable and not at all standardized. Portable programs
can make use of the executable filename where it is available, but
must be prepared to handle the case where it is not.

=== Program command lines

The *command-line* procedure specified in R^6^RS and R^7^RS returns a
list of one or more strings. As with OS command lines, the first
string is by convention the command name. However, `(command-line)` is
generally not the same as the OS command line.

When an implementation is started for the purpose of running a Scheme
program as a batch job, `(command-line)` is most often a tail of the
OS command line such that `(car (command-line))` is the name of the
Scheme program and `(cdr (command-line))` are the arguments given to
that program.

For example, if the OS command line is:

`fantastic-scheme --script program.scm foo bar baz`

the value of `(command-line)` generally is:

`("program.scm" "foo" "bar" "baz")`

Some Schemes support running more than one program in the same batch
job, with the ability to insert a _read-eval-print loop_ in between
any pair of scripts. In that case the command line is given to the
last program in the batch (if any).

When a Scheme program is turned into a standalone executable,
`(command-line)` and the OS command line are generally equivalent.
However, the Scheme implementation's runtime system may omit command
line options that belong to it. For example, Gambit omits the `-:`
option.

In a read-eval-print loop the value of `(command-line)` is not well
specified. A reasonable convention from Chez Scheme is to use a
zero-length string as the command name in this case.

Another ambiguous situation arises when using *load* or *import* to
load some code into an implementation.

=== Taming the complexity

The interface defined by this SRFI is divided into three layers:

* OS layer (*os-executable-file*, *os-command-line*)
* Command layer (*command-line*, *command-name*, *command-args*)
* Script layer (*script-file*, *script-directory*)

The OS layer always concerns the operating system's idea of the
executable.

The command layer applies whenever we are running a Scheme program
that is given its own command line (in the sense that the R^n^RS
*command-line* procedure would return a useful command line concerning
that program specifically). Such a command line is normally a tail of
the OS command line, but may come from other places as well. Kawa
offers a particularly large number of alternative ways to set it.

The script layer applies whenever we are running a Scheme program from
a source file. It does not apply to standalone, pre-compiled programs
or libraries. The idea is that when running simple Scheme scripts, it
is often convenient to have them read and write data files kept in the
same directory as the script itself.

== Specification

=== Terminology

==== Top-level programs

For the purposes of this SRFI, the following *are* considered
_top-level programs_:

* A Scheme program turned into a standalone executable.

* A program whose filename is given on the Scheme implementation's
  command line for the implementation to execute (with or without a
  command line option such as `-s`, `-script`, `--script`, or
  `--program`).

* A file loaded via *load* from the REPL, or from a command line `-e`
  (evaluate expresssion) flag.

The following *are not* considered top-level programs:

* A file loaded via *load* from another file.

* A file loaded implicitly via *import*.

* Code evaluated in a REPL.

* A Scheme source file being _compiled_.

However, implementation-defined global options or optional arguments
are permitted that control whether or not *load* treats files as
top-level programs.

==== Commands and scripts

For the purposes of this SRFI, we classify a running Scheme program as
follows:

* A top-level program given a command line is a _command_.

* A top-level program run from a source file whose filename is known
  to the implementation is a _script_. Note that a file being compiled
  and stored away for later execution is not a script; only a file
  loaded to be evaluated once immediately is a script. The file may
  actually be loaded from a compiled cache, as long as the source
  filename is used to identify it.

A running program can be either a command, a script, both at once, or
neither.

=== OS procedures

(*os-executable-file*) => _string?_

Returns an absolute pathname pointing to the executable file running
the Scheme program. If the Scheme program is running as a standalone
executable, this returns the filename of that executable. Otherwise
this returns the filename of the executable housing the Scheme
implementation. If the Scheme implementation is hosted on top of a
virtual machine such as the JVM or the CLR, the executable filename
will probably point to that virtual machine.

`#f` is returned if no pathname can be retrieved. Some operating
systems do not give the information at all. Some give it in an
unreliable manner which this procedure cannot use. Hence a `#f` return
value is not extraordinary, and portable Scheme code calling this
procedure should be prepared to handle it.

If there is more than one pathname pointing to the executable (e.g.
via symbolic links or hard links), it is undefined which one of them
is returned. The pathname is also not guaranteed to be in a normal
form. Many operating systems have a "realpath" system call to simplify
any given pathname into its most canonical form. Implementations may
or may not use such a procedure to normalize the filename. The only
guarantee from this SRFI is that an absolute instead of relative
filename is returned. An absolute filename is important in case the
program changes its working directory later.

*IMPORTANT:* This problem presents a particularly compelling set of
almost-working solutions to lure implementors onto the rocks. At the
time of writing there is no correct approach that is even moderately
portable. Please be skeptical of any claim that a portable and correct
approach exists.

In particular, all of the following approaches are incorrect.

* Using the current directory (aka the working directory) is liable to
  break all the time. Programs other than simple scripts for personal
  use are rarely started from the directory in which they live;
  starting programs from arbitrary directories using either `PATH`
  lookup or an absolute or relative pathname is common.

* No `argv[0]` based approach works properly. `argv[0]` is simply an
  arbitrary string passed to `execve()` in its _argv_ argument. By
  convention it is the program name. But contrary to popular belief
  there is no mechanism enforcing that convention. Multi-call binaries
  such as `busybox` deliberately take advantage of this lack of
  enforcement - the same executable can be started with any number of
  different names.

* Note that `execve()` takes separate _path_ and _argv_ arguments.
  Only _path_ is checked to see that it points to a real file.
  Lamentably, there is no portable API to retrieve _path_ from within
  the child process. Only _argv_ retrieval is portable.

* When a process is started using its command name, with no directory
  part, directories in `PATH` are traversed to find a matching
  executable. Some programs try to find their own executable by
  replicating a `PATH` search for `argv[0]` when `argv[0]` does not
  contain a directory part. This does not work for two reasons: it's
  trivial to pass a fake `argv[0]`, and even with a truthful `argv[0]`
  the parent process may not have used the same search path that it
  gave to the child process.

* Opening a candidate executable to compute a checksum of its bytes
  and find out whether it is the same as the current executable,
  presents a chicken-and-egg problem: where do you get the checksum
  for the current executable to verify against? It is also possible to
  install multiple copies of the same executable at different
  locations, in which case their checksums would match but not their
  filenames.

The following is a partial list of correct approaches at the time of
writing.

* Darwin (macOS, iOS): `_NSGetExecutablePath()`
* FreeBSD, DragonFly BSD: `sysctl({ CTL_KERN, KERN_PROC, KERN_PROC_PATHNAME, -1 })`
* Linux: `readlink("/proc/self/exe")`
* NetBSD: `sysctl({ CTL_KERN, KERN_PROC_ARGS, -1, KERN_PROC_PATHNAME })`
* OpenBSD: pathname intentionally unavailable
* QNX: read (not readlink) `/proc/self/exefile`
* Solaris: `getexecname()` or `readlink("/proc/self/path/a.out")`
* Windows NT: `GetModuleFileNameW(NULL)`

Most of these procedures take a pre-allocated string buffer and copy
the filename into it. An effective tactic is to call the procedure in
a loop, doubling the size of the buffer at each iteration until the
filename fits or an upper limit is reached.

(*os-command-line*) => _string-list_

Returns the command line of the executable running the Scheme program.
The command line from the operating system is converted to a list of
Scheme strings. No other preprocessing (flag parsing, separating
runtime and script arguments, case conversion, etc.) is performed.

* On Unix, returns a list equivalent to the _argv_ array. Each
  bytevector in _argv_ is converted to a Scheme string based on the
  character encoding prescribed by the current locale. In case the
  locale encoding is unknown or unsupported, *utf8\->string* is an
  acceptable fallback. The implementation should document which
  encodings it supports.

* On Windows NT, returns a list equivalent to passing the string from
   `GetCommandLineW()` to the splitting function
   `CommandLineToArgvW()` and converting the resulting vector of
   UTF-16-LE encoded argument strings to Scheme strings. In principle,
   it is possible to re-implement `CommandLineToArgvW()` entirely in
   Scheme using Scheme strings.

* On Windows NT using the UTF-8 codepage, `GetCommandLineA()` may be
  used to obtain equivalent results. As of this writing there is no
  `CommandLineToArgvA()` in the Windows API; a Scheme equivalent could
  be written.

Please note that `(car (os-command-line))` and `(os-executable-file)`
are two completely different things. The two strings can be equal if
you get lucky, but are not at all interchangeable in principle, and
often not in practice either.

=== Command procedures

(*command-line*) => _string-list_

This procedure is equivalent to the R^6^RS and R^7^RS *command-line*
procedure, but specified in more detail.

*R^6^RS definition:* "Returns a nonempty list of strings. The first
element is an implementation-specific name for the running top-level
program. The remaining elements are command-line arguments according
to the operating system’s conventions."

*R^7^RS definition:* "Returns the command line passed to the process
as a list of strings. The first string corresponds to the command
name, and is implementation-dependent. It is an error to mutate any of
these strings."

*Additional stipulations by this SRFI:*

* If the calling program is *not* a _command_ in this SRFI's
  terminology, a list equal to `("")` is returned.

* If the calling program is a standalone executable, the command name
  is equal to `(car (os-command-line))` with any arguments belonging
  to the Scheme runtime system omitted.

* If the calling program is a Scheme script, the command name is equal
  to the filename given to *load*, on the command line, in an
  environment variable, etc.

* Otherwise, if the command name comes from a filename, the full
  filename is preserved as given to the implementation.

* It is an error to mutate a `(command-line)` list returned by the
  implementation, or any of the strings in it.

* It is permissible to implement *command-line* as a parameter object.
  In that case, the implementation binds the value of the parameter as
  above for the duration of the command. The program may freely rebind
  *command-line* to any other string list containing at least one
  element, either temporarily with *parameterize* or permanently.

* If a program rebinds the *command-line* parameter, the new binding
  may share structure with the old binding.

(*command-name*) => _string?_

Returns a friendly version of `(car (command-line))` evaluated in the
current lexical environment.

If `(car (command-line))` is a zero-length string, `#f` is returned to
indicate "not a command".

Otherwise a friendly command name is typically derived from a filename
as follows:

* The directory part (if any) is removed.

* Filename extensions known to belong to executable files or Scheme
  scripts on the underlying operating system are removed at the
  discretion of the implementation. For example, `.exe` or `.scm`.

* Other changes may also be made according to local conventions.

For example, on Windows `C:\fantastic-scheme-1.0.EXE` would typically
be shortened to `fantastic-scheme-1.0`.

(*command-args*) => _string-list_

Returns `(cdr (command-line))` evaluated in the current lexical
environment.

=== Script procedures

(*script-file*) => _string?_

Returns an absolute pathname pointing to the calling script. Symbolic
links are not resolved.

(The script may or may not be a command; use *command-name* to find
out.)

If the calling program is not a script, `#f` is returned.

Implementations must resolve the absolute pathname of a script before
running that script. The script may change the working directory,
thereby changing the interpretation of relative pathnames.

(*script-directory*) => _string?_

Returns only the directory part of *script-file* as a string. As with
*script-file*, this is an absolute pathname.

Where possible, the string ends with a pathname component separator so
that *string-append* can be easily used to build pathnames based on
it.

If the calling program is not a script, `#f` is returned.

== Implementation

Implementations are in progress for Gauche and Chibi-Scheme.

It is not possible to implement this SRFI based on the R^n^RS
*command-line* procedure. However, the *command-line* from this SRFI
can serve as a conforming implementation of R^n^RS *command-line*.

== Acknowledgements

Thanks to Shiro Kawai for the initial implementation in Gauche, for
patiently reviewing iterations of the design and for valuable feedback
that solved key problems in it. The interplay of *command-line*,
*command-name* and *command-args* was especially tricky to figure out
and I had all but given up hope of a satisfying solution. With Shiro's
insights a simple and natural approach was finally found.

Eryk Sun and Daniel Colascione helped me understand how command lines
actually work on Windows in theory and practice - a surprisingly
complicated topic carrying much historical baggage. With their help,
we are able to select the right API functions to retrieve the OS
command line on that platform.

Gregory Pakosz wrote the _whereami_ library, an instructive collection
of OS-specific solutions to the executable filename problem. Many
people also left useful clues in various Stack Overflow questions.

== References

_The Kawa Scheme language._ Section 21.5 _System inquiry_. Corresponds
to Kawa version 3.1.1.
https://www.gnu.org/software/kawa/System-inquiry.html[Link]

_The Gambit Scheme manual_. Section 2.5 _Scheme scripts_. Corresponds
to Gambit version 4.9.3.
https://www.iro.umontreal.ca/~gambit/doc/gambit.html#Scheme-scripts[Link]

_whereami_ C library by Gregory Pakosz. Retrieved 2020-04-19.
https://github.com/gpakosz/whereami[Link]

_Everyone quotes command line arguments the wrong way._ Daniel
Colascione. "Twisty Little Passages, All Alike" / MSDN Blogs.
Published 2011-04-23. Retrieved 2020-04-19.
https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/[Link]

_Windows API `CommandLineToArgvW` function._ Retrieved 2020-04-19.
https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw[Link].

_environ, execl, execle, execlp, execv, execve, execvp, fexecve -
execute a file_. The Open Group Base Specifications ("POSIX") Issue 7,
2018 edition. IEEE Std 1003.1-2017 (Revision of IEEE Std 1003.1-2008).
https://pubs.opengroup.org/onlinepubs/9699919799/functions/execve.html[Link]
